/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CreateTokenModal: typeof import('./components/CreateTokenModal.vue')['default']
    DashboardSkillItem: typeof import('./components/DashboardSkillItem.vue')['default']
    DemandBadge: typeof import('./components/DemandBadge.vue')['default']
    DemandCard: typeof import('./components/DemandCard.vue')['default']
    DemandsList: typeof import('./components/DemandsList.vue')['default']
    InstallDialog: typeof import('./components/InstallDialog.vue')['default']
    ModerationDialog: typeof import('./components/ModerationDialog.vue')['default']
    MotionBackground: typeof import('./components/MotionBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillCard: typeof import('./components/SkillCard.vue')['default']
    SkillListItem: typeof import('./components/SkillListItem.vue')['default']
    SkillsFilters: typeof import('./components/SkillsFilters.vue')['default']
    SkillsList: typeof import('./components/SkillsList.vue')['default']
    SkillStats: typeof import('./components/SkillStats.vue')['default']
  }
}
